export const ERROR_CODES = {
  // Auth
  INVALID_CREDENTIALS:   'INVALID_CREDENTIALS',
  TOKEN_EXPIRED:         'TOKEN_EXPIRED',
  ACCOUNT_LOCKED:        'ACCOUNT_LOCKED',
  // Patient
  PATIENT_NOT_FOUND:     'PATIENT_NOT_FOUND',
  PATIENT_MRN_EXISTS:    'PATIENT_MRN_EXISTS',
  NATIONAL_ID_EXISTS:    'NATIONAL_ID_EXISTS',
  // Appointment
  SLOT_NOT_AVAILABLE:    'SLOT_NOT_AVAILABLE',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  // General
  UNAUTHORIZED:          'UNAUTHORIZED',
  FORBIDDEN:             'FORBIDDEN',
  NOT_FOUND:             'NOT_FOUND',
  VALIDATION_ERROR:      'VALIDATION_ERROR',
  CONFLICT:              'CONFLICT',
} as const;
