export const PERMISSIONS = {
  PATIENT_CREATE:       'patient:create',
  PATIENT_READ:         'patient:read',
  PATIENT_UPDATE:       'patient:update',
  PATIENT_DELETE:       'patient:delete',
  PATIENT_SEARCH:       'patient:search',
  EMR_READ:             'emr:read',
  EMR_WRITE:            'emr:write',
  EMR_ADDENDUM:         'emr:addendum',
  APPOINTMENT_CREATE:   'appointment:create',
  APPOINTMENT_READ:     'appointment:read',
  APPOINTMENT_CANCEL:   'appointment:cancel',
  QUEUE_READ:           'queue:read',
  QUEUE_CALL_NEXT:      'queue:call_next',
  QUEUE_MANAGE:         'queue:manage',
  PHARMACY_DISPENSE:    'pharmacy:dispense',
  PHARMACY_STOCK_READ:  'pharmacy:stock_read',
  PHARMACY_STOCK_MANAGE:'pharmacy:stock_manage',
  LAB_ORDER_READ:       'lab:order_read',
  LAB_RESULT_ENTER:     'lab:result_enter',
  LAB_RESULT_VALIDATE:  'lab:result_validate',
  BILLING_READ:         'billing:read',
  BILLING_INVOICE:      'billing:invoice',
  BILLING_PAYMENT:      'billing:payment',
  BILLING_DISCOUNT:     'billing:discount',
  USER_MANAGE:          'user:manage',
  ROLE_MANAGE:          'role:manage',
  SETTINGS_MANAGE:      'settings:manage',
  REPORT_VIEW:          'report:view',
  AUDIT_READ:           'audit:read',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
