-- ============================================================
-- MIGRATION 012 — Billing schema
-- Purpose: Invoices, payments, receipts, financial tracking
-- Design: Charges auto-generated by triggers from clinical events
-- ============================================================

-- ── charge_types ─────────────────────────────────────────────
-- Master list of billable item categories.
CREATE TABLE billing.charge_types (
  id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  code         VARCHAR(50)  NOT NULL UNIQUE,
  name         VARCHAR(200) NOT NULL,
  name_fa      VARCHAR(200),
  category     VARCHAR(50)  NOT NULL
                 CHECK (category IN ('consultation','lab','pharmacy','imaging',
                                     'procedure','emergency','room','other')),
  default_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  currency     VARCHAR(3)   DEFAULT 'AFN',
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

INSERT INTO billing.charge_types (code, name, category, default_price) VALUES
  ('CONSULT_GP',    'General Consultation',    'consultation', 200.00),
  ('CONSULT_SPEC',  'Specialist Consultation', 'consultation', 400.00),
  ('EMERG_FEE',     'Emergency Fee',           'emergency',    500.00),
  ('LAB_GENERIC',   'Laboratory Test',         'lab',          150.00),
  ('IMG_XRAY',      'X-Ray',                   'imaging',      300.00),
  ('IMG_ULTRASOUND','Ultrasound',              'imaging',      500.00),
  ('IMG_CT',        'CT Scan',                 'imaging',      2000.00),
  ('IMG_MRI',       'MRI',                     'imaging',      3000.00),
  ('DRUG_GENERIC',  'Medication (generic)',    'pharmacy',     0.00);

-- ── invoices ─────────────────────────────────────────────────
-- One invoice per visit/encounter (can have multiple items).
-- status lifecycle: draft → issued → paid | partial | cancelled | void
CREATE TABLE billing.invoices (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_number VARCHAR(30)  NOT NULL UNIQUE,  -- INV-2024-000001
  patient_id     UUID         NOT NULL REFERENCES patients.patients(id),
  encounter_id   UUID         REFERENCES emr.encounters(id),
  -- Amounts
  subtotal       NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_amount     NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_amount   NUMERIC(12,2) NOT NULL DEFAULT 0,
  paid_amount    NUMERIC(12,2) NOT NULL DEFAULT 0,
  balance_due    NUMERIC(12,2) GENERATED ALWAYS AS (total_amount - paid_amount) STORED,
  currency       VARCHAR(3)   NOT NULL DEFAULT 'AFN',
  -- Status
  status         VARCHAR(20)  NOT NULL DEFAULT 'draft'
                   CHECK (status IN ('draft','issued','partial','paid','cancelled','void')),
  issued_at      TIMESTAMPTZ,
  due_date       DATE,
  paid_at        TIMESTAMPTZ,
  -- Insurance
  insurance_coverage_amount NUMERIC(12,2) DEFAULT 0,
  insurance_claim_id UUID,
  -- Notes
  notes          TEXT,
  -- Base audit
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  created_by     UUID         NOT NULL REFERENCES auth.users(id),
  updated_by     UUID         REFERENCES auth.users(id),
  is_deleted     BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_invoices_patient   ON billing.invoices(patient_id);
CREATE INDEX idx_invoices_encounter ON billing.invoices(encounter_id);
CREATE INDEX idx_invoices_status    ON billing.invoices(status) WHERE is_deleted = FALSE;
CREATE INDEX idx_invoices_date      ON billing.invoices(issued_at DESC);

CREATE TRIGGER invoices_updated_at
  BEFORE UPDATE ON billing.invoices
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER invoices_audit
  AFTER INSERT OR UPDATE OR DELETE ON billing.invoices
  FOR EACH ROW EXECUTE FUNCTION write_audit_log();

-- Auto-generate invoice number
CREATE SEQUENCE billing.invoice_number_seq START 1;

CREATE OR REPLACE FUNCTION generate_invoice_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.invoice_number IS NULL OR NEW.invoice_number = '' THEN
    NEW.invoice_number := 'INV-' ||
      TO_CHAR(NOW(), 'YYYY') || '-' ||
      LPAD(nextval('billing.invoice_number_seq')::TEXT, 6, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_invoice_number
  BEFORE INSERT ON billing.invoices
  FOR EACH ROW EXECUTE FUNCTION generate_invoice_number();

-- ── invoice_items ────────────────────────────────────────────
-- Line items on an invoice. Each service appears as one line.
CREATE TABLE billing.invoice_items (
  id                 UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id         UUID         NOT NULL REFERENCES billing.invoices(id) ON DELETE CASCADE,
  charge_type_id     UUID         REFERENCES billing.charge_types(id),
  description        VARCHAR(300) NOT NULL,
  description_fa     VARCHAR(300),
  quantity           NUMERIC(8,2) NOT NULL DEFAULT 1,
  unit_price         NUMERIC(12,2) NOT NULL,
  discount_percent   NUMERIC(5,2) NOT NULL DEFAULT 0,
  line_total         NUMERIC(12,2) GENERATED ALWAYS AS
                       (quantity * unit_price * (1 - discount_percent / 100)) STORED,
  -- References to the clinical event that generated this charge
  encounter_id       UUID         REFERENCES emr.encounters(id),
  lab_order_id       UUID         REFERENCES emr.lab_orders(id),
  dispensing_id      UUID         REFERENCES pharmacy.dispensing_records(id),
  imaging_order_id   UUID         REFERENCES emr.imaging_orders(id),
  created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_invoice_items_invoice ON billing.invoice_items(invoice_id);

-- Auto-update invoice totals when items change
CREATE OR REPLACE FUNCTION recalculate_invoice_total()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE billing.invoices
  SET
    subtotal     = (SELECT COALESCE(SUM(line_total), 0) FROM billing.invoice_items WHERE invoice_id = COALESCE(NEW.invoice_id, OLD.invoice_id)),
    total_amount = (SELECT COALESCE(SUM(line_total), 0) FROM billing.invoice_items WHERE invoice_id = COALESCE(NEW.invoice_id, OLD.invoice_id)),
    updated_at   = NOW()
  WHERE id = COALESCE(NEW.invoice_id, OLD.invoice_id);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER recalc_total_after_item_change
  AFTER INSERT OR UPDATE OR DELETE ON billing.invoice_items
  FOR EACH ROW EXECUTE FUNCTION recalculate_invoice_total();

-- ── payments ─────────────────────────────────────────────────
CREATE TABLE billing.payments (
  id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id      UUID         NOT NULL REFERENCES billing.invoices(id),
  patient_id      UUID         NOT NULL REFERENCES patients.patients(id),
  amount          NUMERIC(12,2) NOT NULL,
  currency        VARCHAR(3)   NOT NULL DEFAULT 'AFN',
  payment_method  VARCHAR(30)  NOT NULL DEFAULT 'cash'
                    CHECK (payment_method IN ('cash','card','bank_transfer','insurance','mobile_pay','other')),
  reference_number VARCHAR(100),            -- card transaction ID, bank ref etc.
  received_by     UUID         NOT NULL REFERENCES auth.users(id),
  received_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  notes           TEXT,
  is_refunded     BOOLEAN      NOT NULL DEFAULT FALSE,
  refunded_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_payments_invoice ON billing.payments(invoice_id);
CREATE INDEX idx_payments_patient ON billing.payments(patient_id);
CREATE INDEX idx_payments_date    ON billing.payments USING BRIN (received_at);

-- Trigger: update invoice paid_amount and status after each payment
CREATE OR REPLACE FUNCTION update_invoice_after_payment()
RETURNS TRIGGER AS $$
DECLARE
  v_total_paid NUMERIC(12,2);
  v_total      NUMERIC(12,2);
BEGIN
  SELECT COALESCE(SUM(amount),0) INTO v_total_paid
  FROM billing.payments WHERE invoice_id = NEW.invoice_id AND is_refunded = FALSE;

  SELECT total_amount INTO v_total FROM billing.invoices WHERE id = NEW.invoice_id;

  UPDATE billing.invoices SET
    paid_amount = v_total_paid,
    status = CASE
      WHEN v_total_paid >= v_total THEN 'paid'
      WHEN v_total_paid > 0        THEN 'partial'
      ELSE 'issued'
    END,
    paid_at = CASE WHEN v_total_paid >= v_total THEN NOW() ELSE NULL END,
    updated_at = NOW()
  WHERE id = NEW.invoice_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_payment_update_invoice
  AFTER INSERT OR UPDATE ON billing.payments
  FOR EACH ROW EXECUTE FUNCTION update_invoice_after_payment();

-- ── discounts ────────────────────────────────────────────────
-- Discounts require approval above a threshold.
CREATE TABLE billing.discounts (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id      UUID        NOT NULL REFERENCES billing.invoices(id),
  discount_type   VARCHAR(30) NOT NULL CHECK (discount_type IN ('percentage','fixed','full_waiver')),
  amount          NUMERIC(12,2),
  percentage      NUMERIC(5,2),
  reason          TEXT        NOT NULL,
  requested_by    UUID        NOT NULL REFERENCES auth.users(id),
  approved_by     UUID        REFERENCES auth.users(id),
  approved_at     TIMESTAMPTZ,
  status          VARCHAR(20) NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','approved','rejected')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── receipts ─────────────────────────────────────────────────
-- Printable receipt generated after payment.
CREATE TABLE billing.receipts (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  receipt_number  VARCHAR(30) NOT NULL UNIQUE,
  payment_id      UUID        NOT NULL REFERENCES billing.payments(id),
  invoice_id      UUID        NOT NULL REFERENCES billing.invoices(id),
  patient_id      UUID        NOT NULL REFERENCES patients.patients(id),
  amount          NUMERIC(12,2) NOT NULL,
  generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  generated_by    UUID        NOT NULL REFERENCES auth.users(id),
  print_count     INTEGER     NOT NULL DEFAULT 0
);

CREATE SEQUENCE billing.receipt_number_seq START 1;

CREATE OR REPLACE FUNCTION generate_receipt_number()
RETURNS TRIGGER AS $$
BEGIN
  NEW.receipt_number := 'RCP-' ||
    TO_CHAR(NOW(), 'YYYY') || '-' ||
    LPAD(nextval('billing.receipt_number_seq')::TEXT, 6, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_receipt_number
  BEFORE INSERT ON billing.receipts
  FOR EACH ROW EXECUTE FUNCTION generate_receipt_number();